apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-ui
  template:
    metadata:
      labels:
        app: sample-ui
    spec:
      containers:
      - image: minji3262/git-argocd:docker-vue-v0.2
        name: sample-ui
        ports:
        - containerPort: 8080
          protocol: TCP